 'use client';                                                                                                                                                                                             
                                                                                                                                                                                                            
  import { useState, useEffect } from 'react';                                                                                                                                                              
  import { useRouter } from 'next/navigation';                                                                                                                                                              
                                                                                                                                                                                                            
  export default function NewRequestPage() {                                                                                                                                                                
    const router = useRouter();                                                                                                                                                                             
    const [formData, setFormData] = useState({                                                                                                                                                              
      supplier: '',                                                                                                                                                                                         
      description: '',                                                                                                                                                                                      
      amount: '',                                                                                                                                                                                           
      budgetCategory: '',                                                                                                                                                                                   
      budgetSubCategory: '',                                                                                                                                                                                
    });                                                                                                                                                                                                     
    const [budgetStatus, setBudgetStatus] = useState<any>(null);                                                                                                                                            
    const [isChecking, setIsChecking] = useState(false);                                                                                                                                                    
    const [isSubmitting, setIsSubmitting] = useState(false);                                                                                                                                                
                                                                                                                                                                                                            
    // Check budget when amount and category change                                                                                                                                                         
    useEffect(() => {                                                                                                                                                                                       
      const checkBudget = async () => {                                                                                                                                                                     
        if (formData.budgetCategory && formData.amount && parseFloat(formData.amount) > 0) {                                                                                                                
          setIsChecking(true);                                                                                                                                                                              
          try {                                                                                                                                                                                             
            const response = await fetch('/api/budgets/check', {                                                                                                                                            
              method: 'POST',                                                                                                                                                                               
              headers: { 'Content-Type': 'application/json' },                                                                                                                                              
              body: JSON.stringify({                                                                                                                                                                        
                department: formData.budgetCategory,                                                                                                                                                        
                subCategory: formData.budgetSubCategory || null,                                                                                                                                            
                amount: parseFloat(formData.amount),                                                                                                                                                        
              }),                                                                                                                                                                                           
            });                                                                                                                                                                                             
            const data = await response.json();                                                                                                                                                             
            setBudgetStatus(data);                                                                                                                                                                          
          } catch (error) {                                                                                                                                                                                 
            console.error('Budget check failed:', error);                                                                                                                                                   
          } finally {                                                                                                                                                                                       
            setIsChecking(false);                                                                                                                                                                           
          }                                                                                                                                                                                                 
        } else {                                                                                                                                                                                            
          setBudgetStatus(null);                                                                                                                                                                            
        }                                                                                                                                                                                                   
      };                                                                                                                                                                                                    
                                                                                                                                                                                                            
      const timer = setTimeout(checkBudget, 500);                                                                                                                                                           
      return () => clearTimeout(timer);                                                                                                                                                                     
    }, [formData.budgetCategory, formData.budgetSubCategory, formData.amount]);                                                                                                                             
                                                                                                                                                                                                            
    const handleSubmit = async (e: React.FormEvent) => {                                                                                                                                                    
      e.preventDefault();                                                                                                                                                                                   
      setIsSubmitting(true);                                                                                                                                                                                
                                                                                                                                                                                                            
      try {                                                                                                                                                                                                 
        const response = await fetch('/api/requests', {                                                                                                                                                     
          method: 'POST',                                                                                                                                                                                   
          headers: { 'Content-Type': 'application/json' },                                                                                                                                                  
          body: JSON.stringify({                                                                                                                                                                            
            ...formData,                                                                                                                                                                                    
            amount: parseFloat(formData.amount),                                                                                                                                                            
            budgetStatus: budgetStatus?.budget_status || 'no_budget',                                                                                                                                       
          }),                                                                                                                                                                                               
        });                                                                                                                                                                                                 
                                                                                                                                                                                                            
        if (!response.ok) throw new Error('Failed to create request');                                                                                                                                      
                                                                                                                                                                                                            
        alert('Request submitted successfully!');                                                                                                                                                           
        router.push('/');                                                                                                                                                                                   
      } catch (error) {                                                                                                                                                                                     
        alert('Failed to submit request');                                                                                                                                                                  
      } finally {                                                                                                                                                                                           
        setIsSubmitting(false);                                                                                                                                                                             
      }                                                                                                                                                                                                     
    };                                                                                                                                                                                                      
                                                                                                                                                                                                            
    return (                                                                                                                                                                                                
      <div className="min-h-screen bg-gray-50">                                                                                                                                                             
        <div className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">                                                                                                                                       
          <div className="mb-8">                                                                                                                                                                            
            <h1 className="text-3xl font-bold text-gray-900">New Procurement Request</h1>                                                                                                                   
            <p className="mt-2 text-gray-600">                                                                                                                                                              
              Submit a new request with automatic budget validation                                                                                                                                         
            </p>                                                                                                                                                                                            
          </div>                                                                                                                                                                                            
                                                                                                                                                                                                            
          <div className="bg-white shadow-md rounded-lg p-6">                                                                                                                                               
            <form onSubmit={handleSubmit} className="space-y-6">                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Supplier Name *                                                                                                                                                                           
                </label>                                                                                                                                                                                    
                <input                                                                                                                                                                                      
                  type="text"                                                                                                                                                                               
                  required                                                                                                                                                                                  
                  value={formData.supplier}                                                                                                                                                                 
                  onChange={(e) => setFormData({ ...formData, supplier: e.target.value })}                                                                                                                  
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                  placeholder="e.g., Salesforce, AWS, Zoom"                                                                                                                                                 
                />                                                                                                                                                                                          
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Description *                                                                                                                                                                             
                </label>                                                                                                                                                                                    
                <textarea                                                                                                                                                                                   
                  required                                                                                                                                                                                  
                  value={formData.description}                                                                                                                                                              
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}                                                                                                               
                  rows={3}                                                                                                                                                                                  
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                  placeholder="What are you purchasing?"                                                                                                                                                    
                />                                                                                                                                                                                          
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Amount *                                                                                                                                                                                  
                </label>                                                                                                                                                                                    
                <div className="relative">                                                                                                                                                                  
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">                                                                                                    
                    <span className="text-gray-500">$</span>                                                                                                                                                
                  </div>                                                                                                                                                                                    
                  <input                                                                                                                                                                                    
                    type="number"                                                                                                                                                                           
                    required                                                                                                                                                                                
                    min="0"                                                                                                                                                                                 
                    step="0.01"                                                                                                                                                                             
                    value={formData.amount}                                                                                                                                                                 
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}                                                                                                                  
                    className="w-full pl-7 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                               
                    placeholder="25000"                                                                                                                                                                     
                  />                                                                                                                                                                                        
                </div>                                                                                                                                                                                      
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Budget Category *                                                                                                                                                                         
                </label>                                                                                                                                                                                    
                <select                                                                                                                                                                                     
                  required                                                                                                                                                                                  
                  value={formData.budgetCategory}                                                                                                                                                           
                  onChange={(e) => setFormData({ ...formData, budgetCategory: e.target.value })}                                                                                                            
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                >                                                                                                                                                                                           
                  <option value="">Select department...</option>                                                                                                                                            
                  <option value="Engineering">Engineering</option>                                                                                                                                          
                  <option value="Sales">Sales</option>                                                                                                                                                      
                  <option value="Marketing">Marketing</option>                                                                                                                                              
                  <option value="IT">IT</option>                                                                                                                                                            
                  <option value="HR">HR</option>                                                                                                                                                            
                  <option value="Finance">Finance</option>                                                                                                                                                  
                </select>                                                                                                                                                                                   
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Sub-category                                                                                                                                                                              
                </label>                                                                                                                                                                                    
                <input                                                                                                                                                                                      
                  type="text"                                                                                                                                                                               
                  value={formData.budgetSubCategory}                                                                                                                                                        
                  onChange={(e) => setFormData({ ...formData, budgetSubCategory: e.target.value })}                                                                                                         
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                  placeholder="e.g., Software, Hardware"                                                                                                                                                    
                />                                                                                                                                                                                          
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              {/* Budget Status Display */}                                                                                                                                                                 
              {isChecking && (                                                                                                                                                                              
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">                                                                                                                          
                  <div className="flex items-center">                                                                                                                                                       
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-indigo-600 mr-3"></div>                                                                                             
                    <span className="text-sm text-blue-900">Checking budget availability...</span>                                                                                                          
                  </div>                                                                                                                                                                                    
                </div>                                                                                                                                                                                      
              )}                                                                                                                                                                                            
                                                                                                                                                                                                            
              {budgetStatus && !isChecking && (                                                                                                                                                             
                <div                                                                                                                                                                                        
                  className={`border rounded-lg p-4 ${                                                                                                                                                      
                    budgetStatus.budget_found                                                                                                                                                               
                      ? budgetStatus.budget_status === 'in_budget'                                                                                                                                          
                        ? 'bg-green-50 border-green-200'                                                                                                                                                    
                        : 'bg-yellow-50 border-yellow-200'                                                                                                                                                  
                      : 'bg-red-50 border-red-200'                                                                                                                                                          
                  }`}                                                                                                                                                                                       
                >                                                                                                                                                                                           
                  <div className="flex items-start">                                                                                                                                                        
                    <div className="flex-shrink-0">                                                                                                                                                         
                      {budgetStatus.budget_found ? (                                                                                                                                                        
                        budgetStatus.budget_status === 'in_budget' ? (                                                                                                                                      
                          <svg className="h-5 w-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">                                                                                                  
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 
1.414l2 2a1 1 0 001.414 0l4-4z"              
  clipRule="evenodd" />                                                                                                                                                                                     
                          </svg>                                                                                                                                                                            
                        ) : (                                                                                                                                                                               
                          <svg className="h-5 w-5 text-yellow-600" fill="currentColor" viewBox="0 0 20 20">                                                                                                 
                            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 
0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0
   1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />                                                                                                                      
                          </svg>                                                                                                                                                                            
                        )                                                                                                                                                                                   
                      ) : (                                                                                                                                                                                 
                        <svg className="h-5 w-5 text-red-600" fill="currentColor" viewBox="0 0 20 20">                                                                                                      
                          <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 
1.414L10 11.414l1.293 1.293a1 1 0              
  001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />                                                                                                     
                        </svg>                                                                                                                                                                              
                      )}                                                                                                                                                                                    
                    </div>                                                                                                                                                                                  
                    <div className="ml-3 flex-1">                                                                                                                                                           
                      <h3 className="text-sm font-medium">                                                                                                                                                  
                        {budgetStatus.budget_found                                                                                                                                                          
                          ? budgetStatus.budget_status === 'in_budget'                                                                                                                                      
                            ? '✓ This request is in budget'                                                                                                                                                 
                            : '⚠ Budget exceeded'                                                                                                                                                           
                          : '✗ No budget found'}                                                                                                                                                            
                      </h3>                                                                                                                                                                                 
                      {budgetStatus.budget_found && budgetStatus.budget_details && (                                                                                                                        
                        <div className="mt-2 text-sm space-y-1">                                                                                                                                            
                          <div className="flex justify-between">                                                                                                                                            
                            <span>Request amount:</span>                                                                                                                                                    
                            <span className="font-medium">${parseFloat(formData.amount).toLocaleString()}</span>                                                                                            
                          </div>                                                                                                                                                                            
                          <div className="flex justify-between">                                                                                                                                            
                            <span>Budget available:</span>                                                                                                                                                  
                            <span className="font-medium">${budgetStatus.budget_details.available_amount?.toLocaleString()}</span>                                                                          
                          </div>                                                                                                                                                                            
                          <div className="flex justify-between">                                                                                                                                            
                            <span>Current utilization:</span>                                                                                                                                               
                            <span className="font-medium">{budgetStatus.budget_details.utilization_pct?.toFixed(0)}%</span>                                                                                 
                          </div>                                                                                                                                                                            
                          <div className="w-full bg-gray-200 rounded-full h-2 mt-2">                                                                                                                        
                            <div                                                                                                                                                                            
                              className={`h-2 rounded-full ${                                                                                                                                               
                                budgetStatus.budget_details.new_utilization_pct >= 90                                                                                                                       
                                  ? 'bg-red-500'                                                                                                                                                            
                                  : budgetStatus.budget_details.new_utilization_pct >= 75                                                                                                                   
                                  ? 'bg-yellow-500'                                                                                                                                                         
                                  : 'bg-green-500'                                                                                                                                                          
                              }`}                                                                                                                                                                           
                              style={{                                                                                                                                                                      
                                width: `${Math.min(budgetStatus.budget_details.new_utilization_pct || 0, 100)}%`,                                                                                           
                              }}                                                                                                                                                                            
                            ></div>                                                                                                                                                                         
                          </div>                                                                                                                                                                            
                        </div>                                                                                                                                                                              
                      )}                                                                                                                                                                                    
                    </div>                                                                                                                                                                                  
                  </div>                                                                                                                                                                                    
                </div>                                                                                                                                                                                      
              )}                                                                                                                                                                                            
                                                                                                                                                                                                            
              <div className="flex gap-4 pt-4">                                                                                                                                                             
                <button                                                                                                                                                                                     
                  type="submit"                                                                                                                                                                             
                  disabled={isSubmitting}                                                                                                                                                                   
                  className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:bg-gray-400 disabled:cursor-not-allowed 
transition"                                          
                >                                                                                                                                                                                           
                  {isSubmitting ? 'Submitting...' : 'Submit Request'}                                                                                                                                       
                </button>                                                                                                                                                                                   
                <button                                                                                                                                                                                     
                  type="button"                                                                                                                                                                             
                  onClick={() => router.push('/')}                                                                                                                                                          
                  className="px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 transition"                                                                                                       
                >                                                                                                                                                                                           
                  Cancel                                                                                                                                                                                    
                </button>                                                                                                                                                                                   
              </div>                                                                                                                                                                                        
            </form>                                                                                                                                                                                         
          </div>                                                                                                                                                                                            
        </div>                                                                                                                                                                                              
      </div>                                                                                                                                                                                                
    );                                                                                                                                                                                                      
  } 
