import type { Metadata } from "next";                                                                                                                                                                     
  import "./globals.css";                                                                                                                                                                                   
                                                                                                                                                                                                            
  export const metadata: Metadata = {                                                                                                                                                                       
    title: "SpendFlo Budget Module",                                                                                                                                                                        
    description: "Budget management and validation system",                                                                                                                                                 
  };                                                                                                                                                                                                        
                                                                                                                                                                                                            
  export default function RootLayout({                                                                                                                                                                      
    children,                                                                                                                                                                                               
  }: Readonly<{                                                                                                                                                                                             
    children: React.ReactNode;                                                                                                                                                                              
  }>) {                                                                                                                                                                                                     
    return (                                                                                                                                                                                                
      <html lang="en">                                                                                                                                                                                      
        <body className="antialiased">                                                                                                                                                                      
          <nav className="bg-indigo-600 text-white shadow-lg">                                                                                                                                              
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">                                                                                                                                        
              <div className="flex justify-between h-16">                                                                                                                                                   
                <div className="flex items-center space-x-8">                                                                                                                                               
                  <a href="/" className="text-xl font-bold">                                                                                                                                                
                    SpendFlo                                                                                                                                                                                
                  </a>                                                                                                                                                                                      
                  <a href="/dashboard" className="hover:text-indigo-200 transition">                                                                                                                          
                    Budgets                                                                                                                                                                                 
                  </a>                                                                                                                                                                                      
                  <a href="/business/request-v2" className="hover:text-indigo-200 transition">                                                                                                                     
                    New Request                                                                                                                                                                             
                  </a>                                                                                                                                                                                      
                </div>                                                                                                                                                                                      
                <div className="flex items-center">                                                                                                                                                         
                  <span className="text-sm">Demo User</span>                                                                                                                                                
                </div>                                                                                                                                                                                      
              </div>                                                                                                                                                                                        
            </div>                                                                                                                                                                                          
          </nav>                                                                                                                                                                                            
          {children}                                                                                                                                                                                        
        </body>                                                                                                                                                                                             
      </html>                                                                                                                                                                                               
    );                                                                                                                                                                                                      
  } 
