 'use client';                                                                                                                                                                                             
                                                                                                                                                                                                            
  import { useState } from 'react';                                                                                                                                                                         
  import { useRouter } from 'next/navigation';                                                                                                                                                              
                                                                                                                                                                                                            
  export default function NewBudgetPage() {                                                                                                                                                                 
    const router = useRouter();                                                                                                                                                                             
    const [formData, setFormData] = useState({                                                                                                                                                              
      department: '',                                                                                                                                                                                       
      subCategory: '',                                                                                                                                                                                      
      budgetedAmount: '',                                                                                                                                                                                   
      fiscalPeriod: 'FY2025',                                                                                                                                                                               
    });                                                                                                                                                                                                     
    const [isSubmitting, setIsSubmitting] = useState(false);                                                                                                                                                
    const [error, setError] = useState('');                                                                                                                                                                 
                                                                                                                                                                                                            
    const handleSubmit = async (e: React.FormEvent) => {                                                                                                                                                    
      e.preventDefault();                                                                                                                                                                                   
      setIsSubmitting(true);                                                                                                                                                                                
      setError('');                                                                                                                                                                                         
                                                                                                                                                                                                            
      try {                                                                                                                                                                                                 
        const response = await fetch('/api/budgets', {                                                                                                                                                      
          method: 'POST',                                                                                                                                                                                   
          headers: { 'Content-Type': 'application/json' },                                                                                                                                                  
          body: JSON.stringify({                                                                                                                                                                            
            ...formData,                                                                                                                                                                                    
            budgetedAmount: parseFloat(formData.budgetedAmount),                                                                                                                                            
          }),                                                                                                                                                                                               
        });                                                                                                                                                                                                 
                                                                                                                                                                                                            
        if (!response.ok) {                                                                                                                                                                                 
          throw new Error('Failed to create budget');                                                                                                                                                       
        }                                                                                                                                                                                                   
                                                                                                                                                                                                            
        router.push('/budgets');                                                                                                                                                                            
        router.refresh();                                                                                                                                                                                   
      } catch (err) {                                                                                                                                                                                       
        setError(err instanceof Error ? err.message : 'Something went wrong');                                                                                                                              
      } finally {                                                                                                                                                                                           
        setIsSubmitting(false);                                                                                                                                                                             
      }                                                                                                                                                                                                     
    };                                                                                                                                                                                                      
                                                                                                                                                                                                            
    return (                                                                                                                                                                                                
      <div className="min-h-screen bg-gray-50">                                                                                                                                                             
        <div className="max-w-3xl mx-auto px-4 py-8 sm:px-6 lg:px-8">                                                                                                                                       
          <div className="mb-8">                                                                                                                                                                            
            <h1 className="text-3xl font-bold text-gray-900">Create New Budget</h1>                                                                                                                         
            <p className="mt-2 text-gray-600">                                                                                                                                                              
              Add a new budget for a department or category                                                                                                                                                 
            </p>                                                                                                                                                                                            
          </div>                                                                                                                                                                                            
                                                                                                                                                                                                            
          <div className="bg-white shadow-md rounded-lg p-6">                                                                                                                                               
            <form onSubmit={handleSubmit} className="space-y-6">                                                                                                                                            
              {error && (                                                                                                                                                                                   
                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">                                                                                                            
                  {error}                                                                                                                                                                                   
                </div>                                                                                                                                                                                      
              )}                                                                                                                                                                                            
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Department *                                                                                                                                                                              
                </label>                                                                                                                                                                                    
                <input                                                                                                                                                                                      
                  type="text"                                                                                                                                                                               
                  required                                                                                                                                                                                  
                  value={formData.department}                                                                                                                                                               
                  onChange={(e) =>                                                                                                                                                                          
                    setFormData({ ...formData, department: e.target.value })                                                                                                                                
                  }                                                                                                                                                                                         
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                  placeholder="e.g., Engineering, Sales, Marketing"                                                                                                                                         
                />                                                                                                                                                                                          
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Sub-category                                                                                                                                                                              
                </label>                                                                                                                                                                                    
                <input                                                                                                                                                                                      
                  type="text"                                                                                                                                                                               
                  value={formData.subCategory}                                                                                                                                                              
                  onChange={(e) =>                                                                                                                                                                          
                    setFormData({ ...formData, subCategory: e.target.value })                                                                                                                               
                  }                                                                                                                                                                                         
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                  placeholder="e.g., Software, Hardware, Services"                                                                                                                                          
                />                                                                                                                                                                                          
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Budgeted Amount *                                                                                                                                                                         
                </label>                                                                                                                                                                                    
                <div className="relative">                                                                                                                                                                  
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">                                                                                                    
                    <span className="text-gray-500">$</span>                                                                                                                                                
                  </div>                                                                                                                                                                                    
                  <input                                                                                                                                                                                    
                    type="number"                                                                                                                                                                           
                    required                                                                                                                                                                                
                    min="0"                                                                                                                                                                                 
                    step="0.01"                                                                                                                                                                             
                    value={formData.budgetedAmount}                                                                                                                                                         
                    onChange={(e) =>                                                                                                                                                                        
                      setFormData({ ...formData, budgetedAmount: e.target.value })                                                                                                                          
                    }                                                                                                                                                                                       
                    className="w-full pl-7 pr-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                               
                    placeholder="50000"                                                                                                                                                                     
                  />                                                                                                                                                                                        
                </div>                                                                                                                                                                                      
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div>                                                                                                                                                                                         
                <label className="block text-sm font-medium text-gray-700 mb-2">                                                                                                                            
                  Fiscal Period *                                                                                                                                                                           
                </label>                                                                                                                                                                                    
                <select                                                                                                                                                                                     
                  required                                                                                                                                                                                  
                  value={formData.fiscalPeriod}                                                                                                                                                             
                  onChange={(e) =>                                                                                                                                                                          
                    setFormData({ ...formData, fiscalPeriod: e.target.value })                                                                                                                              
                  }                                                                                                                                                                                         
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"                                                                      
                >                                                                                                                                                                                           
                  <option value="FY2025">FY2025</option>                                                                                                                                                    
                  <option value="FY2026">FY2026</option>                                                                                                                                                    
                  <option value="Q1-2025">Q1 2025</option>                                                                                                                                                  
                  <option value="Q2-2025">Q2 2025</option>                                                                                                                                                  
                  <option value="Q3-2025">Q3 2025</option>                                                                                                                                                  
                  <option value="Q4-2025">Q4 2025</option>                                                                                                                                                  
                </select>                                                                                                                                                                                   
              </div>                                                                                                                                                                                        
                                                                                                                                                                                                            
              <div className="flex gap-4 pt-4">                                                                                                                                                             
                <button                                                                                                                                                                                     
                  type="submit"                                                                                                                                                                             
                  disabled={isSubmitting}                                                                                                                                                                   
                  className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:bg-gray-400 disabled:cursor-not-allowed 
transition"                                          
                >                                                                                                                                                                                           
                  {isSubmitting ? 'Creating...' : 'Create Budget'}                                                                                                                                          
                </button>                                                                                                                                                                                   
                <button                                                                                                                                                                                     
                  type="button"                                                                                                                                                                             
                  onClick={() => router.push('/budgets')}                                                                                                                                                   
                  className="px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 transition"                                                                                                       
                >                                                                                                                                                                                           
                  Cancel                                                                                                                                                                                    
                </button>                                                                                                                                                                                   
              </div>                                                                                                                                                                                        
            </form>                                                                                                                                                                                         
          </div>                                                                                                                                                                                            
        </div>                                                                                                                                                                                              
      </div>                                                                                                                                                                                                
    );                                                                                                                                                                                                      
  }
